// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: onnx/onnx-operators-ml.proto3
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Onnx {

  /// <summary>Holder for reflection information generated from onnx/onnx-operators-ml.proto3</summary>
  public static partial class OnnxOperatorsMlReflection {

    #region Descriptor
    /// <summary>File descriptor for onnx/onnx-operators-ml.proto3</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static OnnxOperatorsMlReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ch1vbm54L29ubngtb3BlcmF0b3JzLW1sLnByb3RvMxIEb25ueBoTb25ueC9v",
            "bm54LW1sLnByb3RvMyLvAQoNRnVuY3Rpb25Qcm90bxIMCgRuYW1lGAEgASgJ",
            "EhUKDXNpbmNlX3ZlcnNpb24YAiABKAMSJAoGc3RhdHVzGAMgASgOMhQub25u",
            "eC5PcGVyYXRvclN0YXR1cxINCgVpbnB1dBgEIAMoCRIOCgZvdXRwdXQYBSAD",
            "KAkSEQoJYXR0cmlidXRlGAYgAygJEh0KBG5vZGUYByADKAsyDy5vbm54Lk5v",
            "ZGVQcm90bxISCgpkb2Nfc3RyaW5nGAggASgJEi4KDG9wc2V0X2ltcG9ydBgJ",
            "IAMoCzIYLm9ubnguT3BlcmF0b3JTZXRJZFByb3RvInEKDU9wZXJhdG9yUHJv",
            "dG8SDwoHb3BfdHlwZRgBIAEoCRIVCg1zaW5jZV92ZXJzaW9uGAIgASgDEiQK",
            "BnN0YXR1cxgDIAEoDjIULm9ubnguT3BlcmF0b3JTdGF0dXMSEgoKZG9jX3N0",
            "cmluZxgKIAEoCSL5AQoQT3BlcmF0b3JTZXRQcm90bxINCgVtYWdpYxgBIAEo",
            "CRISCgppcl92ZXJzaW9uGAIgASgDEh0KFWlyX3ZlcnNpb25fcHJlcmVsZWFz",
            "ZRgDIAEoCRIZChFpcl9idWlsZF9tZXRhZGF0YRgHIAEoCRIOCgZkb21haW4Y",
            "BCABKAkSFQoNb3BzZXRfdmVyc2lvbhgFIAEoAxISCgpkb2Nfc3RyaW5nGAYg",
            "ASgJEiUKCG9wZXJhdG9yGAggAygLMhMub25ueC5PcGVyYXRvclByb3RvEiYK",
            "CWZ1bmN0aW9ucxgJIAMoCzITLm9ubnguRnVuY3Rpb25Qcm90byouCg5PcGVy",
            "YXRvclN0YXR1cxIQCgxFWFBFUklNRU5UQUwQABIKCgZTVEFCTEUQAUICSANi",
            "BnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Onnx.OnnxMlReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Onnx.OperatorStatus), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Onnx.FunctionProto), global::Onnx.FunctionProto.Parser, new[]{ "Name", "SinceVersion", "Status", "Input", "Output", "Attribute", "Node", "DocString", "OpsetImport" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Onnx.OperatorProto), global::Onnx.OperatorProto.Parser, new[]{ "OpType", "SinceVersion", "Status", "DocString" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Onnx.OperatorSetProto), global::Onnx.OperatorSetProto.Parser, new[]{ "Magic", "IrVersion", "IrVersionPrerelease", "IrBuildMetadata", "Domain", "OpsetVersion", "DocString", "Operator", "Functions" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  /// <summary>
  /// Operator/function status.
  /// </summary>
  public enum OperatorStatus {
    [pbr::OriginalName("EXPERIMENTAL")] Experimental = 0,
    [pbr::OriginalName("STABLE")] Stable = 1,
  }

  #endregion

  #region Messages
  public sealed partial class FunctionProto : pb::IMessage<FunctionProto> {
    private static readonly pb::MessageParser<FunctionProto> _parser = new pb::MessageParser<FunctionProto>(() => new FunctionProto());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<FunctionProto> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Onnx.OnnxOperatorsMlReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public FunctionProto() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public FunctionProto(FunctionProto other) : this() {
      name_ = other.name_;
      sinceVersion_ = other.sinceVersion_;
      status_ = other.status_;
      input_ = other.input_.Clone();
      output_ = other.output_.Clone();
      attribute_ = other.attribute_.Clone();
      node_ = other.node_.Clone();
      docString_ = other.docString_;
      opsetImport_ = other.opsetImport_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public FunctionProto Clone() {
      return new FunctionProto(this);
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 1;
    private string name_ = "";
    /// <summary>
    /// The name of the function, similar usage of op_type in OperatorProto.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "since_version" field.</summary>
    public const int SinceVersionFieldNumber = 2;
    private long sinceVersion_;
    /// <summary>
    /// The first version of a function set which contains this function.
    /// When there's any breaking change for this function, the function set
    /// contains the function needs to bump its version, and since_version of
    /// the updated function will be changed to the updated function set version.  
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long SinceVersion {
      get { return sinceVersion_; }
      set {
        sinceVersion_ = value;
      }
    }

    /// <summary>Field number for the "status" field.</summary>
    public const int StatusFieldNumber = 3;
    private global::Onnx.OperatorStatus status_ = global::Onnx.OperatorStatus.Experimental;
    /// <summary>
    /// This field indicates whether the syntax, semantics, or presence
    /// of this function is in an experimental or stable stage. Once an
    /// function is published as STABLE, its syntax and semantics MUST NOT
    /// change in subsequent versions of the operator set.
    /// When a function is published as EXPERIMENTAL, the syntax and semantics
    /// of the function MAY change across operator set versions.
    /// Functions "become" stable by deprecating the experimental version and
    /// introducing a new stable function with the same name.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Onnx.OperatorStatus Status {
      get { return status_; }
      set {
        status_ = value;
      }
    }

    /// <summary>Field number for the "input" field.</summary>
    public const int InputFieldNumber = 4;
    private static readonly pb::FieldCodec<string> _repeated_input_codec
        = pb::FieldCodec.ForString(34);
    private readonly pbc::RepeatedField<string> input_ = new pbc::RepeatedField<string>();
    /// <summary>
    /// The inputs and outputs of the function.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<string> Input {
      get { return input_; }
    }

    /// <summary>Field number for the "output" field.</summary>
    public const int OutputFieldNumber = 5;
    private static readonly pb::FieldCodec<string> _repeated_output_codec
        = pb::FieldCodec.ForString(42);
    private readonly pbc::RepeatedField<string> output_ = new pbc::RepeatedField<string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<string> Output {
      get { return output_; }
    }

    /// <summary>Field number for the "attribute" field.</summary>
    public const int AttributeFieldNumber = 6;
    private static readonly pb::FieldCodec<string> _repeated_attribute_codec
        = pb::FieldCodec.ForString(50);
    private readonly pbc::RepeatedField<string> attribute_ = new pbc::RepeatedField<string>();
    /// <summary>
    /// The attributes of the function.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<string> Attribute {
      get { return attribute_; }
    }

    /// <summary>Field number for the "node" field.</summary>
    public const int NodeFieldNumber = 7;
    private static readonly pb::FieldCodec<global::Onnx.NodeProto> _repeated_node_codec
        = pb::FieldCodec.ForMessage(58, global::Onnx.NodeProto.Parser);
    private readonly pbc::RepeatedField<global::Onnx.NodeProto> node_ = new pbc::RepeatedField<global::Onnx.NodeProto>();
    /// <summary>
    /// The nodes in the function.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Onnx.NodeProto> Node {
      get { return node_; }
    }

    /// <summary>Field number for the "doc_string" field.</summary>
    public const int DocStringFieldNumber = 8;
    private string docString_ = "";
    /// <summary>
    /// A human-readable documentation for this function. Markdown is allowed.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string DocString {
      get { return docString_; }
      set {
        docString_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "opset_import" field.</summary>
    public const int OpsetImportFieldNumber = 9;
    private static readonly pb::FieldCodec<global::Onnx.OperatorSetIdProto> _repeated_opsetImport_codec
        = pb::FieldCodec.ForMessage(74, global::Onnx.OperatorSetIdProto.Parser);
    private readonly pbc::RepeatedField<global::Onnx.OperatorSetIdProto> opsetImport_ = new pbc::RepeatedField<global::Onnx.OperatorSetIdProto>();
    /// <summary>
    /// The OperatorSets this function body (graph) relies on.
    /// A FunctionProto body (graph) may implicitly rely on the OperatorSet that
    /// this function belongs to. It can also explicitly rely on more OperatorSets
    /// with this field specified.
    ///
    /// All nodes in the function body (graph) will bind against the operator
    /// with the same-domain/same-op_type operator with the HIGHEST version
    /// in the referenced operator sets. This means at most one version can be relied
    /// for one domain.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Onnx.OperatorSetIdProto> OpsetImport {
      get { return opsetImport_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as FunctionProto);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(FunctionProto other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Name != other.Name) return false;
      if (SinceVersion != other.SinceVersion) return false;
      if (Status != other.Status) return false;
      if(!input_.Equals(other.input_)) return false;
      if(!output_.Equals(other.output_)) return false;
      if(!attribute_.Equals(other.attribute_)) return false;
      if(!node_.Equals(other.node_)) return false;
      if (DocString != other.DocString) return false;
      if(!opsetImport_.Equals(other.opsetImport_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (SinceVersion != 0L) hash ^= SinceVersion.GetHashCode();
      if (Status != global::Onnx.OperatorStatus.Experimental) hash ^= Status.GetHashCode();
      hash ^= input_.GetHashCode();
      hash ^= output_.GetHashCode();
      hash ^= attribute_.GetHashCode();
      hash ^= node_.GetHashCode();
      if (DocString.Length != 0) hash ^= DocString.GetHashCode();
      hash ^= opsetImport_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Name.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Name);
      }
      if (SinceVersion != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(SinceVersion);
      }
      if (Status != global::Onnx.OperatorStatus.Experimental) {
        output.WriteRawTag(24);
        output.WriteEnum((int) Status);
      }
      input_.WriteTo(output, _repeated_input_codec);
      output_.WriteTo(output, _repeated_output_codec);
      attribute_.WriteTo(output, _repeated_attribute_codec);
      node_.WriteTo(output, _repeated_node_codec);
      if (DocString.Length != 0) {
        output.WriteRawTag(66);
        output.WriteString(DocString);
      }
      opsetImport_.WriteTo(output, _repeated_opsetImport_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (SinceVersion != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(SinceVersion);
      }
      if (Status != global::Onnx.OperatorStatus.Experimental) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Status);
      }
      size += input_.CalculateSize(_repeated_input_codec);
      size += output_.CalculateSize(_repeated_output_codec);
      size += attribute_.CalculateSize(_repeated_attribute_codec);
      size += node_.CalculateSize(_repeated_node_codec);
      if (DocString.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(DocString);
      }
      size += opsetImport_.CalculateSize(_repeated_opsetImport_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(FunctionProto other) {
      if (other == null) {
        return;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      if (other.SinceVersion != 0L) {
        SinceVersion = other.SinceVersion;
      }
      if (other.Status != global::Onnx.OperatorStatus.Experimental) {
        Status = other.Status;
      }
      input_.Add(other.input_);
      output_.Add(other.output_);
      attribute_.Add(other.attribute_);
      node_.Add(other.node_);
      if (other.DocString.Length != 0) {
        DocString = other.DocString;
      }
      opsetImport_.Add(other.opsetImport_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Name = input.ReadString();
            break;
          }
          case 16: {
            SinceVersion = input.ReadInt64();
            break;
          }
          case 24: {
            Status = (global::Onnx.OperatorStatus) input.ReadEnum();
            break;
          }
          case 34: {
            input_.AddEntriesFrom(input, _repeated_input_codec);
            break;
          }
          case 42: {
            output_.AddEntriesFrom(input, _repeated_output_codec);
            break;
          }
          case 50: {
            attribute_.AddEntriesFrom(input, _repeated_attribute_codec);
            break;
          }
          case 58: {
            node_.AddEntriesFrom(input, _repeated_node_codec);
            break;
          }
          case 66: {
            DocString = input.ReadString();
            break;
          }
          case 74: {
            opsetImport_.AddEntriesFrom(input, _repeated_opsetImport_codec);
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// An OperatorProto represents the immutable specification of the signature
  /// and semantics of an operator.
  ///
  /// Operators are declared as part of an OperatorSet, which also defines the
  /// domain name for the set.
  ///
  /// Operators are uniquely identified by a three part identifier
  ///   (domain, op_type, since_version)
  /// where
  ///   *domain* is the domain of an operator set that
  ///      contains this operator specification.
  ///
  ///   *op_type* is the name of the operator as referenced by a
  ///      NodeProto.op_type
  ///
  ///   *since_version* is the version of the operator set that
  ///      this operator was initially declared in.
  /// </summary>
  public sealed partial class OperatorProto : pb::IMessage<OperatorProto> {
    private static readonly pb::MessageParser<OperatorProto> _parser = new pb::MessageParser<OperatorProto>(() => new OperatorProto());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<OperatorProto> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Onnx.OnnxOperatorsMlReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public OperatorProto() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public OperatorProto(OperatorProto other) : this() {
      opType_ = other.opType_;
      sinceVersion_ = other.sinceVersion_;
      status_ = other.status_;
      docString_ = other.docString_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public OperatorProto Clone() {
      return new OperatorProto(this);
    }

    /// <summary>Field number for the "op_type" field.</summary>
    public const int OpTypeFieldNumber = 1;
    private string opType_ = "";
    /// <summary>
    /// The name of the operator within a domain.
    /// This field MUST be present in this version of the IR.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string OpType {
      get { return opType_; }
      set {
        opType_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "since_version" field.</summary>
    public const int SinceVersionFieldNumber = 2;
    private long sinceVersion_;
    /// <summary>
    /// The version of the operator set that first introduced this
    /// operator. This value MUST be the same value as the
    /// opset_version of the operator set that first published this operator.
    /// Subsequent versions of the operator set MUST NOT alter the signature
    /// or semantics of the operator once published as STABLE.
    /// This field MUST be present in this version of the IR.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long SinceVersion {
      get { return sinceVersion_; }
      set {
        sinceVersion_ = value;
      }
    }

    /// <summary>Field number for the "status" field.</summary>
    public const int StatusFieldNumber = 3;
    private global::Onnx.OperatorStatus status_ = global::Onnx.OperatorStatus.Experimental;
    /// <summary>
    /// This field indicates whether the syntax, semantics, or presence
    /// of this operator is in an experimental or stable stage. Once an
    /// operator is published as STABLE, it's syntax and semantics MUST NOT
    /// change in subsequent versions of the operator set.
    /// When an operator is published as EXPERIMENTAL, the syntax and semantics
    /// of the operator MAY change across operator set versions.
    /// Operators "become" stable by deprecating the experimental version and
    /// introducing a new stable operator with the same op_type.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Onnx.OperatorStatus Status {
      get { return status_; }
      set {
        status_ = value;
      }
    }

    /// <summary>Field number for the "doc_string" field.</summary>
    public const int DocStringFieldNumber = 10;
    private string docString_ = "";
    /// <summary>
    /// A human-readable documentation for this operator. Markdown is allowed.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string DocString {
      get { return docString_; }
      set {
        docString_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as OperatorProto);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(OperatorProto other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (OpType != other.OpType) return false;
      if (SinceVersion != other.SinceVersion) return false;
      if (Status != other.Status) return false;
      if (DocString != other.DocString) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (OpType.Length != 0) hash ^= OpType.GetHashCode();
      if (SinceVersion != 0L) hash ^= SinceVersion.GetHashCode();
      if (Status != global::Onnx.OperatorStatus.Experimental) hash ^= Status.GetHashCode();
      if (DocString.Length != 0) hash ^= DocString.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (OpType.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(OpType);
      }
      if (SinceVersion != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(SinceVersion);
      }
      if (Status != global::Onnx.OperatorStatus.Experimental) {
        output.WriteRawTag(24);
        output.WriteEnum((int) Status);
      }
      if (DocString.Length != 0) {
        output.WriteRawTag(82);
        output.WriteString(DocString);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (OpType.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(OpType);
      }
      if (SinceVersion != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(SinceVersion);
      }
      if (Status != global::Onnx.OperatorStatus.Experimental) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Status);
      }
      if (DocString.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(DocString);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(OperatorProto other) {
      if (other == null) {
        return;
      }
      if (other.OpType.Length != 0) {
        OpType = other.OpType;
      }
      if (other.SinceVersion != 0L) {
        SinceVersion = other.SinceVersion;
      }
      if (other.Status != global::Onnx.OperatorStatus.Experimental) {
        Status = other.Status;
      }
      if (other.DocString.Length != 0) {
        DocString = other.DocString;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            OpType = input.ReadString();
            break;
          }
          case 16: {
            SinceVersion = input.ReadInt64();
            break;
          }
          case 24: {
            Status = (global::Onnx.OperatorStatus) input.ReadEnum();
            break;
          }
          case 82: {
            DocString = input.ReadString();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// An OperatorSetProto represents an immutable set of immutable operator
  /// specifications.
  ///
  /// The domain of the set (OperatorSetProto.domain) is a reverse-DNS name
  /// that disambiguates operator sets defined by independent entities.
  ///
  /// The version of the set (opset_version) is a monotonically increasing
  /// integer that indicates changes to the membership of the operator set.
  ///
  /// Operator sets are uniquely identified by a two part identifier (domain, opset_version)
  ///
  /// Like ModelProto, OperatorSetProto is intended as a top-level file/wire format,
  /// and thus has the standard format headers in addition to the operator set information.
  /// </summary>
  public sealed partial class OperatorSetProto : pb::IMessage<OperatorSetProto> {
    private static readonly pb::MessageParser<OperatorSetProto> _parser = new pb::MessageParser<OperatorSetProto>(() => new OperatorSetProto());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<OperatorSetProto> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Onnx.OnnxOperatorsMlReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public OperatorSetProto() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public OperatorSetProto(OperatorSetProto other) : this() {
      magic_ = other.magic_;
      irVersion_ = other.irVersion_;
      irVersionPrerelease_ = other.irVersionPrerelease_;
      irBuildMetadata_ = other.irBuildMetadata_;
      domain_ = other.domain_;
      opsetVersion_ = other.opsetVersion_;
      docString_ = other.docString_;
      operator_ = other.operator_.Clone();
      functions_ = other.functions_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public OperatorSetProto Clone() {
      return new OperatorSetProto(this);
    }

    /// <summary>Field number for the "magic" field.</summary>
    public const int MagicFieldNumber = 1;
    private string magic_ = "";
    /// <summary>
    /// All OperatorSetProtos start with a distingushed byte sequence to disambiguate
    /// protobuf files containing OperatorSets from other content.
    /// This field MUST be "ONNXOPSET"
    /// This field MUST be present in this version of the IR
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Magic {
      get { return magic_; }
      set {
        magic_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "ir_version" field.</summary>
    public const int IrVersionFieldNumber = 2;
    private long irVersion_;
    /// <summary>
    /// All OperatorSetProtos indicate the version of the IR syntax and semantics
    /// they adhere to. It is always IR_VERSION.
    /// This field MUST be present in this version of the IR
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long IrVersion {
      get { return irVersion_; }
      set {
        irVersion_ = value;
      }
    }

    /// <summary>Field number for the "ir_version_prerelease" field.</summary>
    public const int IrVersionPrereleaseFieldNumber = 3;
    private string irVersionPrerelease_ = "";
    /// <summary>
    /// The prerelease component of the SemVer of the IR.
    /// This field MAY be absent in this version of the IR
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string IrVersionPrerelease {
      get { return irVersionPrerelease_; }
      set {
        irVersionPrerelease_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "ir_build_metadata" field.</summary>
    public const int IrBuildMetadataFieldNumber = 7;
    private string irBuildMetadata_ = "";
    /// <summary>
    /// The build metadata component of the SemVer of the IR.
    /// This field MAY be absent in this version of the IR
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string IrBuildMetadata {
      get { return irBuildMetadata_; }
      set {
        irBuildMetadata_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "domain" field.</summary>
    public const int DomainFieldNumber = 4;
    private string domain_ = "";
    /// <summary>
    /// Domain name of the operator set, in reverse DNS form (e.g., com.acme.dnnops).
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Domain {
      get { return domain_; }
      set {
        domain_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "opset_version" field.</summary>
    public const int OpsetVersionFieldNumber = 5;
    private long opsetVersion_;
    /// <summary>
    /// The version of the set of operators. This is a simple int value
    /// that is monotonically increasing as new versions of operator set
    /// are published. All operators in this set MUST have version
    /// numbers no greater than opset_version.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long OpsetVersion {
      get { return opsetVersion_; }
      set {
        opsetVersion_ = value;
      }
    }

    /// <summary>Field number for the "doc_string" field.</summary>
    public const int DocStringFieldNumber = 6;
    private string docString_ = "";
    /// <summary>
    /// A human-readable documentation for this set of operators. Markdown is allowed.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string DocString {
      get { return docString_; }
      set {
        docString_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "operator" field.</summary>
    public const int OperatorFieldNumber = 8;
    private static readonly pb::FieldCodec<global::Onnx.OperatorProto> _repeated_operator_codec
        = pb::FieldCodec.ForMessage(66, global::Onnx.OperatorProto.Parser);
    private readonly pbc::RepeatedField<global::Onnx.OperatorProto> operator_ = new pbc::RepeatedField<global::Onnx.OperatorProto>();
    /// <summary>
    /// The operators specified by this operator set.
    /// The (name, version) MUST be unique across all OperatorProtos in operator
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Onnx.OperatorProto> Operator {
      get { return operator_; }
    }

    /// <summary>Field number for the "functions" field.</summary>
    public const int FunctionsFieldNumber = 9;
    private static readonly pb::FieldCodec<global::Onnx.FunctionProto> _repeated_functions_codec
        = pb::FieldCodec.ForMessage(74, global::Onnx.FunctionProto.Parser);
    private readonly pbc::RepeatedField<global::Onnx.FunctionProto> functions_ = new pbc::RepeatedField<global::Onnx.FunctionProto>();
    /// <summary>
    /// The functions specified by this operator set.
    /// The (name, version) MUST be unique across all OperatorProtos/FunctionProtos in operator/functions
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Onnx.FunctionProto> Functions {
      get { return functions_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as OperatorSetProto);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(OperatorSetProto other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Magic != other.Magic) return false;
      if (IrVersion != other.IrVersion) return false;
      if (IrVersionPrerelease != other.IrVersionPrerelease) return false;
      if (IrBuildMetadata != other.IrBuildMetadata) return false;
      if (Domain != other.Domain) return false;
      if (OpsetVersion != other.OpsetVersion) return false;
      if (DocString != other.DocString) return false;
      if(!operator_.Equals(other.operator_)) return false;
      if(!functions_.Equals(other.functions_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Magic.Length != 0) hash ^= Magic.GetHashCode();
      if (IrVersion != 0L) hash ^= IrVersion.GetHashCode();
      if (IrVersionPrerelease.Length != 0) hash ^= IrVersionPrerelease.GetHashCode();
      if (IrBuildMetadata.Length != 0) hash ^= IrBuildMetadata.GetHashCode();
      if (Domain.Length != 0) hash ^= Domain.GetHashCode();
      if (OpsetVersion != 0L) hash ^= OpsetVersion.GetHashCode();
      if (DocString.Length != 0) hash ^= DocString.GetHashCode();
      hash ^= operator_.GetHashCode();
      hash ^= functions_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Magic.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Magic);
      }
      if (IrVersion != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(IrVersion);
      }
      if (IrVersionPrerelease.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(IrVersionPrerelease);
      }
      if (Domain.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Domain);
      }
      if (OpsetVersion != 0L) {
        output.WriteRawTag(40);
        output.WriteInt64(OpsetVersion);
      }
      if (DocString.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(DocString);
      }
      if (IrBuildMetadata.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(IrBuildMetadata);
      }
      operator_.WriteTo(output, _repeated_operator_codec);
      functions_.WriteTo(output, _repeated_functions_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Magic.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Magic);
      }
      if (IrVersion != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(IrVersion);
      }
      if (IrVersionPrerelease.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(IrVersionPrerelease);
      }
      if (IrBuildMetadata.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(IrBuildMetadata);
      }
      if (Domain.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Domain);
      }
      if (OpsetVersion != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(OpsetVersion);
      }
      if (DocString.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(DocString);
      }
      size += operator_.CalculateSize(_repeated_operator_codec);
      size += functions_.CalculateSize(_repeated_functions_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(OperatorSetProto other) {
      if (other == null) {
        return;
      }
      if (other.Magic.Length != 0) {
        Magic = other.Magic;
      }
      if (other.IrVersion != 0L) {
        IrVersion = other.IrVersion;
      }
      if (other.IrVersionPrerelease.Length != 0) {
        IrVersionPrerelease = other.IrVersionPrerelease;
      }
      if (other.IrBuildMetadata.Length != 0) {
        IrBuildMetadata = other.IrBuildMetadata;
      }
      if (other.Domain.Length != 0) {
        Domain = other.Domain;
      }
      if (other.OpsetVersion != 0L) {
        OpsetVersion = other.OpsetVersion;
      }
      if (other.DocString.Length != 0) {
        DocString = other.DocString;
      }
      operator_.Add(other.operator_);
      functions_.Add(other.functions_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Magic = input.ReadString();
            break;
          }
          case 16: {
            IrVersion = input.ReadInt64();
            break;
          }
          case 26: {
            IrVersionPrerelease = input.ReadString();
            break;
          }
          case 34: {
            Domain = input.ReadString();
            break;
          }
          case 40: {
            OpsetVersion = input.ReadInt64();
            break;
          }
          case 50: {
            DocString = input.ReadString();
            break;
          }
          case 58: {
            IrBuildMetadata = input.ReadString();
            break;
          }
          case 66: {
            operator_.AddEntriesFrom(input, _repeated_operator_codec);
            break;
          }
          case 74: {
            functions_.AddEntriesFrom(input, _repeated_functions_codec);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
